language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules

env:
  global:
  - NODE_ENV=test

services:
  # - postgresql

before_install:
  # - psql -c 'CREATE DATABASE big_thing_test;' -U postgres

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
  - ./cc-test-reporter after-build
